spring.application.name=taskmanger

# JWT
security.jwt.secret-key=${JWT_SECRET_KEY:<paste openssl rand -base64 32 output here>}
security.jwt.expiration-time=3600000
spring.config.import=optional:file:.env[.properties]