CREATE TABLE tasks (
    task_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    priority    VARCHAR(20),
    title       VARCHAR(255) UNIQUE,
    description VARCHAR(2000),
    due_date    TIMESTAMP NOT NULL
);
